# Generated by Django 4.0.1 on 2022-03-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_task_user_alter_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
