# Generated by Django 4.0.1 on 2022-03-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_comitt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comitt',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
