# Generated by Django 4.0.1 on 2022-03-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_delete_comitt_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_comentario', models.CharField(max_length=255)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
