# Generated by Django 4.0.1 on 2022-05-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_curso_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursofaq', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.curso')),
            ],
        ),
    ]
