# Generated by Django 4.0.1 on 2022-05-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_cursofaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntasFrequentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('curso_faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.curso')),
            ],
        ),
    ]
