# Generated by Django 4.0.1 on 2022-05-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_perguntasfrequentes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerguntasFrequentes',
            new_name='Perguntas',
        ),
    ]
