# Generated by Django 4.0.1 on 2022-05-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_rename_perguntasfrequentes_perguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntas',
            name='curso_faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cursofaq'),
        ),
    ]
