# Generated by Django 4.0.1 on 2022-05-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_conteudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursofaq',
            old_name='curso',
            new_name='cursosnome',
        ),
    ]
