# Generated by Django 4.0.1 on 2022-05-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_rename_curso_cursofaq_cursosnome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursofaq',
            old_name='cursofaq',
            new_name='nomecurso',
        ),
    ]
