# Generated by Django 4.0.1 on 2022-05-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_rename_cursofaq_cursofaq_nomecurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntas',
            name='curso_faq',
        ),
        migrations.AddField(
            model_name='perguntas',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='principal.curso'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CursoFaq',
        ),
    ]
