# Generated by Django 4.0.1 on 2022-05-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_remove_perguntas_curso_faq_perguntas_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntas',
            old_name='curso',
            new_name='cursos',
        ),
    ]
