# Generated by Django 4.0.1 on 2022-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_remove_perguntas_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
