# Generated by Django 4.0.1 on 2022-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_perguntas_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntas',
            name='cursos',
        ),
        migrations.AddField(
            model_name='perguntas',
            name='done',
            field=models.CharField(choices=[('Google', 'Google'), ('Microsoft', 'Microsoft'), ('Web', 'Web')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
