# Generated by Django 4.0.1 on 2022-05-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_remove_perguntas_cursos_perguntas_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntas',
            old_name='done',
            new_name='nome_curso',
        ),
    ]
