# Generated by Django 4.0.1 on 2022-05-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_rename_done_perguntas_nome_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.topico'),
        ),
    ]
