# Generated by Django 4.0.1 on 2022-05-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_comentario_topico_delete_comentarios_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Resposta',
        ),
    ]
