# Generated by Django 4.0.1 on 2022-05-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_remove_resposta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='user',
        ),
    ]
