# Generated by Django 4.0.1 on 2022-05-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_topico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='user',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
