# Generated by Django 4.0.1 on 2022-05-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0031_resposta_user_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='user_resposta',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='user',
        ),
    ]
