# Generated by Django 4.0.1 on 2022-05-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0033_resposta_user_topico_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_introducao', models.CharField(max_length=255)),
                ('introducao', models.CharField(max_length=255)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.conteudo')),
            ],
        ),
    ]
