# Generated by Django 4.0.1 on 2022-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0034_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='primeiro_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='primeiro_passo_titulo',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
