# Generated by Django 4.0.1 on 2022-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0035_material_primeiro_passo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='segundo_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
