# Generated by Django 4.0.1 on 2022-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_material_segundo_passo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quarto_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='quinto_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='setimo_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='sexto_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='terceira_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
