# Generated by Django 4.0.1 on 2022-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0037_material_quarto_passo_material_quinto_passo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='decimo_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='doze_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='nono_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='oitavo_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='onze_passo',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
