# Generated by Django 4.0.1 on 2022-06-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0039_conteudo_introducao_conteudo_titulo_introducao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico1',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico2',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico3',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico4',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico5',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico6',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico7',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conteudo',
            name='titulo_topico8',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
