# Generated by Django 4.0.1 on 2022-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0041_conteudo_topico1_conteudo_topico2_conteudo_topico3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='introducao',
            field=models.TextField(),
        ),
    ]
